version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logueando en Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Construyendo imágenes Docker..."
      - docker build -t servicio-alternativas ./servicio-alternativas
      - docker build -t servicio-boletas ./servicio-boletas
      - docker build -t servicio-commons ./servicio-commons
      - docker build -t servicio-consultas ./servicio-consultas
      - docker build -t servicio-eureka-server ./servicio-eureka-server
      - docker build -t servicio-gateway-server ./servicio-gateway-server
      - echo "Taggeando imágenes..."
      - docker tag servicio-alternativas:latest <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/servicio-alternativas:latest
      - docker tag servicio-boletas:latest <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/servicio-boletas:latest
      - docker tag servicio-commons:latest <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/servicio-commons:latest
      - docker tag servicio-consultas:latest <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/servicio-consultas:latest
      - docker tag servicio-eureka-server:latest <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/servicio-eureka-server:latest
      - docker tag servicio-gateway-server:latest <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/servicio-gateway-server:latest
  post_build:
    commands:
      - echo "Subiendo imágenes a ECR..."
      - docker push <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/servicio-alternativas:latest
      - docker push <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/servicio-boletas:latest
      - docker push <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/servicio-commons:latest
      - docker push <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/servicio-consultas:latest
      - docker push <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/servicio-eureka-server:latest
      - docker push <TU_ID_CUENTA>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/servicio-gateway-server:latest

artifacts:
  files: '**/*'
